[atom]
id = "simple"
version = "0.1.0"
src = "src"

[fetch.local-lib]
local = true

[fetch.nixpkgs-atom]

[fetch.nixpkgs]
name = "nixpkgs"
import = true

[fetch.nixpkgs-flake]
name = "nixpkgs"
flake = true

[fetch.nixos-lib]
name = "nixpkgs"
subdir = "nixos/lib"
import = true

[fetch.lib]
name = "nixpkgs"
subdir = "lib"
import = true

[features]
default = ["system"]

[backend.nix]
fetcher = "npins"