[atom]
id = "simple"
version = "0.1.0"

[fetch.pkgs]
name = "nixpkgs"
import = true
args = [{ localSystem = "x86_64-linux" }]

[core]
features = ["std"]
[std]
features = ["lib"]

[backend.nix]
# default when `eka` cli is ready
# fetcher = "native"
fetcher = "npins"

[fetcher.npins]
root = "npins"
