[atom]
id = "simple"
version = "0.1.0"
src = "src"

[fetch.local-lib]
type = "local"

[fetch.nixpkgs-atom]

[fetch.nixpkgs]
name = "nixpkgs"
type = "import"

[fetch.nixpkgs-flake]
name = "nixpkgs"
type = "flake"

[fetch.nixos-lib]
name = "nixpkgs"
type = "import"
subdir = "nixos/lib"

[fetch.lib]
name = "nixpkgs"
type = "import"
subdir = "lib"

[features]
default = ["system"]

[backend.nix]
fetcher = "npins"