[atom]
id = "simple"
version = "0.1.0"

[fetch.nixpkgs]
name = "nixpkgs"
import = true

[fetch.nixos-lib]
name = "nixpkgs"
subdir = "nixos/lib"
import = true

[fetch.lib]
name = "nixpkgs"
subdir = "lib"
import = true

# TODO find out if this is necessary
[core]
features = ["std"]
[std]
features = ["lib"]

[backend.nix]
# default when `eka` cli is ready
# fetcher = "native"
fetcher = "npins"