[atom]
id = "simple"
version = "0.1.0"
src = "src"
propagate = true
system = true

[fetch.local-lib]
type = "local"

[fetch.nixpkgs-atom]

[fetch.nixpkgs]
name = "nixpkgs"
type = "import"

[fetch.nixpkgs-flake]
name = "nixpkgs"
type = "flake"

[fetch.nixos-lib]
name = "nixpkgs"
type = "import"
subdir = "nixos/lib"

[fetch.lib]
name = "nixpkgs"
type = "import"
subdir = "lib"

[fetch.flake-atom]
type = "flake"
optional = true

[features]
flake = ["flake-atom"]

[backend.nix]
fetcher = "npins"